import {validateV6} from './recording-codec.js';
import { expandRecording } from './recording.js';
export class RecordingStore {
 async open(){if(this.db)return this.db;this.db=await new Promise((resolve,reject)=>{const r=indexedDB.open('tavernweave-gundam-war',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('chunks'))r.result.createObjectStore('chunks',{keyPath:['id','index']});if(!r.result.objectStoreNames.contains('recordings'))r.result.createObjectStore('recordings',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('录像库被另一个页面占用'));});return this.db;}
 async transact(mode,action){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('recordings',mode);let result;const r=action(tx.objectStore('recordings'));r.onsuccess=()=>result=r.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('录像保存中止'));});}
 async list(includePending=false){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('recordings','readonly'),rows=[],cursor=tx.objectStore('recordings').openCursor();cursor.onsuccess=()=>{const c=cursor.result;if(c){const {id,name,createdAt,schemaVersion}=c.value;if(includePending||!c.value.pending)rows.push({id,name,createdAt,schemaVersion,...(includePending?{pending:!!c.value.pending}:{})});c.continue();}};tx.oncomplete=()=>resolve(rows.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))));tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('录像库读取中止'));});}
 async batch(mode,values){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction(['recordings','chunks'],'readwrite'),records=tx.objectStore('recordings'),chunks=tx.objectStore('chunks');for(const value of values){const id=mode==='delete'?value:value.id;if(mode==='delete'){records.delete(id);chunks.delete(IDBKeyRange.bound([id,0],[id,Number.MAX_SAFE_INTEGER]));}else if(value.schemaVersion===6&&value.chunks){const {chunks:blocks,...header}=value;records.put(header);chunks.delete(IDBKeyRange.bound([id,0],[id,Number.MAX_SAFE_INTEGER]));for(const block of blocks)chunks.put({id,...block});}else records.put(value);}tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('录像批量操作中止'));});}
 deleteMany(ids){return this.batch('delete',ids);}
 putMany(records){return this.batch('put',records);}
 async recoverPending(){let recovered=0,empty=0;for(const row of (await this.list(true)).filter(r=>r.pending)){const header=await this.transact('readonly',s=>s.get(row.id)),chunks=await this.chunkRows(row.id);if(!chunks.length){empty++;continue;}const duration=chunks.at(-1).frames.at(-1)[0],restored={...header,pending:false,partial:true,frameCount:chunks.reduce((n,c)=>n+c.frames.length,0),chunkCount:chunks.length,duration,result:{reason:'interrupted',winner:null,t:duration},name:header.name.slice(0,150)+'（中断记录）'};validateV6({...restored,chunks});await this.put(restored);recovered++;}return{recovered,empty};}
 async get(id){const value=await this.transact('readonly',s=>s.get(id));if(value?.schemaVersion!==6||value.chunks)return value;const chunks=await this.chunkRows(id);return {...value,chunks};}
 async chunkRows(id){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('chunks','readonly'),r=tx.objectStore('chunks').getAll(IDBKeyRange.bound([id,0],[id,Number.MAX_SAFE_INTEGER]));tx.oncomplete=()=>resolve(r.result.map(({id,...block})=>block));tx.onerror=()=>reject(tx.error);});}
 async putChunk(id,block){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('chunks','readwrite');tx.objectStore('chunks').put({id,...block});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('录像块写入中止'));});}
 async put(value){if(value.schemaVersion!==6||!value.chunks)return this.transact('readwrite',s=>s.put(value));const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction(['recordings','chunks'],'readwrite');const {chunks,...header}=value;tx.objectStore('recordings').put(header);tx.objectStore('chunks').delete(IDBKeyRange.bound([value.id,0],[value.id,Number.MAX_SAFE_INTEGER]));for(const block of chunks)tx.objectStore('chunks').put({id:value.id,...block});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
 async delete(id){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction(['recordings','chunks'],'readwrite');tx.objectStore('recordings').delete(id);tx.objectStore('chunks').delete(IDBKeyRange.bound([id,0],[id,Number.MAX_SAFE_INTEGER]));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
 close(){this.db?.close();this.db=null;}
}
export function validateRecording(r){
 if(r?.schemaVersion===6)return validateV6(r);
 if(r?.schemaVersion===5){validateRecording(expandRecording(r));return r;}
 const fail=message=>{throw Error('录像无效：'+message);};
 if(!r||![2,3,4].includes(r.schemaVersion)||typeof r.name!=='string'||r.name.length>160||!Array.isArray(r.frames)||!r.frames.length||r.frames.length>10000||!Array.isArray(r.events)||r.events.length>20000)fail('格式或容量');
 for(const key of ['sky','horizon','sea'])if(!/^#[0-9a-f]{6}$/i.test(r.environment?.visual?.[key]))fail('环境');
 const vector=v=>Array.isArray(v)&&v.length===3&&v.every(x=>typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<1e8);
 const effect=e=>{if(!e||!['beam','tracer','slash','clash','notice','impact','explosion','dodge-jet'].includes(e.type)||!Number.isFinite(e.t)||e.t<0||e.t>1801||!Number.isFinite(e.life)||e.life<=0||e.life>10)fail('特效');if(['beam','tracer','slash'].includes(e.type)?(!vector(e.from)||!vector(e.to)):!vector(e.position))fail('特效坐标');if(e.type==='dodge-jet'&&!vector(e.direction))fail('喷气方向');if(e.type==='clash'&&(!Number.isFinite(e.intensity)||e.intensity<0||e.intensity>1))fail('拼刀强度');if(e.severity!==undefined&&(!Number.isFinite(e.severity)||e.severity<0||e.severity>1))fail('受击强度');if(e.losses!==undefined&&(!e.losses||typeof e.losses!=='object'||Array.isArray(e.losses)||Object.values(e.losses).some(x=>!Number.isFinite(x)||x<0||x>1)))fail('拼刀掉稳');if(e.type==='notice'&&(typeof e.text!=='string'||e.text.length>120||!['info','good','warning','damage'].includes(e.tone)))fail('提示文字');};
 if(r.effects!==undefined){if(!Array.isArray(r.effects)||r.effects.length>30000)fail('特效记录容量');r.effects.forEach(effect);}
 let t=-1;
  for(const f of r.frames){if(!Number.isInteger(f.tick)||f.tick<0||!Number.isFinite(f.t)||f.t<t||f.t<0||f.t>1801||!Array.isArray(f.units)||f.units.length<2||f.units.length>48||!Array.isArray(f.effects)||f.effects.length>Math.max(300,f.units.length*12))fail('帧数据');t=f.t;
  const ids=new Set();
  for(const u of f.units){const legacy=r.schemaVersion<4&&['a','b'].includes(u.id),modern=/^[ab]-\d+-\d+$/.test(u.id)&&['a','b'].includes(u.side);if((!legacy&&!modern)||ids.has(u.id)||!vector(u.position)||!vector(u.velocity)||!vector(u.forward))fail('单位');ids.add(u.id);
   for(const k of ['name','pilot','pilotState','weapon','order'])if(typeof u[k]!=='string'||u[k].length>160)fail('单位文字');
   for(const k of ['armor','maxArmor','structure','maxStructure','energy','maxEnergy','track','shots','hits','damage','radius'])if(typeof u[k]!=='number'||!Number.isFinite(u[k])||u[k]<0||u[k]>1e8)fail('单位数值');
   if(r.schemaVersion>=3){if(!Array.isArray(u.weapons)||!u.weapons.length||u.weapons.length>16||typeof u.threat!=='string'||u.threat.length>160||!u.fireArc||!Number.isFinite(u.fireArc.yaw)||!Number.isFinite(u.fireArc.pitch))fail('武装与射界');for(const w of u.weapons)if(typeof w.name!=='string'||w.name.length>100||!Number.isInteger(w.ammo)||!Number.isFinite(w.readyIn))fail('武装状态');}
   if(u.maxStructure<=0||u.maxEnergy<=0)fail('容量');
   for(const key of ['totalEnergy','maxTotalEnergy','energyRecoveryRate'])if(u[key]!==undefined&&(!Number.isFinite(u[key])||u[key]<0||u[key]>1e8))fail('能源储量');if(u.totalEnergy!==undefined&&(u.energy>u.totalEnergy+.02||u.totalEnergy>u.maxTotalEnergy+.02))fail('能源守恒');
   if(u.speedRate!==undefined&&(!Number.isFinite(u.speedRate)||Math.abs(u.speedRate)>1e8))fail('加减速数值');
  }
  f.effects.forEach(effect);
  if(f.projectiles!==undefined){if(!Array.isArray(f.projectiles)||f.projectiles.length>192)fail('导弹容量');for(const p of f.projectiles)if(!vector(p.position)||!vector(p.previous)||!Array.isArray(p.trace)||p.trace.length>10||p.trace.some(v=>!vector(v)))fail('导弹轨迹');}
 }
 for(const e of r.events)if(!Number.isFinite(e.t)||e.t<0||e.t>1801||typeof e.text!=='string'||e.text.length>2000||typeof e.type!=='string')fail('日志');return r;
}
