import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {Battle} from '../simulation.js';import {parseWorldbook} from '../domain.js';import {composeWorldbooks} from '../worldbook-stack.js';import {arbitrateStrategy} from '../decision-arbiter.js';import {initializeSkills,updateSkills,skillWindow} from '../pilot-skills.js';
const load=async f=>JSON.parse(await fs.readFile(new URL('../'+f,import.meta.url),'utf8')),c=parseWorldbook(composeWorldbooks([{name:'SEED',book:await load('worldbook-seed.json')},{name:'00',book:await load('worldbook-00.json')}]));
let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
const mock={t:1,random:()=>.99},u={targetId:'b',pilotState:{sim:{composure:.95,tracking:.95}},operationalPlan:{id:'shot',until:3},weapons:[{attack:{targetId:'b',at:1.4}}]},tactics={planSwitchMargin:1.5,strategyTieMargin:.25};
check('small score fluctuations cannot cancel a live attack',()=>assert.equal(arbitrateStrategy(mock,u,[{id:'shot',priority:0,score:20},{id:'orbit',priority:0,score:23}],tactics).id,'shot'));
check('a real defensive emergency preempts a committed attack',()=>assert.equal(arbitrateStrategy(mock,u,[{id:'shot',priority:0,score:50},{id:'dodge',priority:2,score:8}],tactics).id,'dodge'));
check('invalid previous plans are never held',()=>assert.equal(arbitrateStrategy(mock,u,[{id:'orbit',priority:0,score:8}],tactics).id,'orbit'));
check('a prepared follow-through gets the same bounded commitment as a windup',()=>{const blade={...u,weapons:[],bladeFollowUp:{targetId:'b',until:2},operationalPlan:{id:'follow',until:1},};assert.equal(arbitrateStrategy(mock,blade,[{id:'follow',mode:'follow',priority:0,score:20},{id:'orbit',priority:0,score:26}],tactics).id,'follow');});
check('a major tactical improvement can replace a live attack',()=>assert.equal(arbitrateStrategy(mock,u,[{id:'shot',priority:0,score:10},{id:'orbit',priority:0,score:28}],tactics).id,'orbit'));
const force=(m,p='elite-pilot')=>({machineId:m,pilotId:p,stateId:'standard',count:1,strategy:'attack'}),plan=(a,b,distance=1500)=>({environmentId:'space',battlefieldId:'pursuit-space',missionId:'annihilation',distanceM:distance,altitudeM:0,focus:'overall',mode:'auto',aForces:[a],bForces:[b],maxSeconds:100});
check('per-battle skill toggles disable a template skill without changing the catalog',()=>{const actor=force('seed-duel');actor.pilotOptions={skills:{'elite-fire-discipline':false,'elite-blade-tempo':false}};const battle=new Battle(c,plan(actor,force('seed-duel')),17);assert.equal(battle.units[0].skillRuntime.definitions.length,0);assert.equal(c.pilots.find(p=>p.id==='elite-pilot').states[0].skills['elite-fire-discipline'],true);});
const b=new Battle(c,plan(force('seed-duel'),force('seed-duel')),17);b.step();const [a,z]=b.units;a.targetId=z.id;a.position=[0,0,0];z.position=[1500,0,0];a.forward=[1,0,0];a.contacts.set(z.id,{position:[1500,0,0],velocity:[0,0,0],forward:[-1,0,0],observedAt:b.t});a.stability=.8;a.evadeUntil=0;a.microControlUntil=0;const rifle=a.weapons.find(w=>w.definition.kind==='beam');rifle.fireControl={targetId:z.id,locked:true};rifle.readyAt=b.t;a.skillRuntime=null;
check('immobile entities never attempt a powered tail-break maneuver',()=>{const old=a.machine.sim.maxSpeedMps;a.machine.sim.maxSpeedMps=0;assert.equal(b.proactiveBreakaway(a,z,false),null);a.machine.sim.maxSpeedMps=old;});
const skill=c.skillTemplates.find(x=>x.id==='elite-fire-discipline');a.pilotState.skills={[skill.id]:true};initializeSkills(b,a,[skill]);const initial=a.pilotState.sim.aim;
check('a valid fire-control window activates the ranged skill',()=>{assert.ok(skillWindow(b,a,skill.activationGate));updateSkills(b,a);assert.ok(a.skillRuntime.active.has(skill.id));assert.ok(a.pilotState.sim.aim>initial);});
check('the skill does not reactivate during cooldown or stack its multiplier',()=>{b.t+=skill.durationS+.21;updateSkills(b,a);assert.ok(a.skillRuntime.recovering.has(skill.id));assert.ok(!a.skillRuntime.active.has(skill.id));assert.equal(a.pilotState.sim.aim,initial);assert.ok(Object.values(a.pilotState.sim).every(Number.isFinite));updateSkills(b,a);assert.equal(a.pilotState.sim.aim,initial);});
check('window skills cannot run on stale enemy positions',()=>{a.contacts.get(z.id).observedAt=b.t-2;assert.equal(skillWindow(b,a,'ranged-window'),false);});
const rows=[];for(const [m,p,enemy,count,energy]of [['seed-duel','elite-pilot','seed-duel',1,1],['seed-duel','ace-pilot','seed-duel',1,1],['seed-duel','ace-pilot','seed-duel',1,.2],['seed-duel','elite-pilot','seed-duel',3,1],['ad-exia','ace-pilot','seed-justice',1,1]])for(const seed of [17,29,53]){
 const scenario=plan(force(m,p),force(enemy,p),1200);scenario.aForces[0].count=count;scenario.bForces[0].count=count;
 const battle=new Battle(c,scenario,seed);for(const x of battle.units)x.energy*=energy;let cancelled=0,started=0,changes=0;const last=new Map(),cancel=battle.cancelAttacks.bind(battle);battle.cancelAttacks=x=>{cancelled+=x.weapons.filter(w=>w.attack||w.salvo).length;cancel(x);};
 while(battle.t<100&&!battle.result){const before=battle.events.length;battle.step();for(const e of battle.events.slice(before))if(e.type==='shot')started++;for(const x of battle.units){assert.ok([...x.position,...x.velocity,x.energy,x.stability,...Object.values(x.pilotState.sim)].every(Number.isFinite));if(last.has(x.id)&&last.get(x.id)!==x.lastStrategyId)changes++;last.set(x.id,x.lastStrategyId);}}
 rows.push({machine:m,pilot:p,units:count*2,initialEnergy:energy,seed,t:+battle.t.toFixed(2),winner:battle.result?.winner??null,shots:started,cancelled,strategyChanges:changes,skills:[...new Set(battle.events.filter(e=>e.type==='skill').map(e=>e.skill))],skillActivations:battle.events.filter(e=>e.type==='skill').length,bladeShots:battle.events.filter(e=>e.type==='shot'&&e.kind==='melee').length});assert.ok(started>0);
}
assert.ok(rows.some(r=>r.skills.some(id=>id==='elite-fire-discipline')));assert.ok(rows.some(r=>r.skills.some(id=>id==='ace-blade-pressure')));
console.log(JSON.stringify({checks,rows}));
