import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {renameWorldbook,validWorldbookName,remapRenamedScenario} from '../worldbook-rename.js';import {composeWorldbooks} from '../worldbook-stack.js';import {parseWorldbook,validateScenario} from '../domain.js';import {referenceOrigin} from '../catalog-names.js';
let checks=0;async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
await check('invalid names and Windows reserved names are rejected',()=>{for(const s of ['','../x','x/y','NUL','con.json','x.'])assert.throws(()=>validWorldbookName(s));assert.equal(validWorldbookName(' 新资料书 '),'新资料书');});
const originalFetch=globalThis.fetch;function fixture(fail=false){const data={entries:{0:{uid:0,content:'untouched',custom:{z:1,a:2}}}},books=new Map([['旧书',data]]),card={avatar:'fixture.png',name:'测试角色',data:{extensions:{world:'旧书'}}},extra={extraBooks:['旧书','其他书']},power={persona_description_lorebook:'旧书',persona_descriptions:{fixture:{lorebook:'旧书'}}};let globals=['其他书','旧书'],metadataSaves=0;
 const context={characters:[card],powerUserSettings:power,chatMetadata:{world_info:'旧书'},getRequestHeaders:()=>({}),saveWorldInfo:async(name,data)=>books.set(name,structuredClone(data)),updateWorldInfoList:async()=>{},saveSettingsDebounced:()=>{},saveMetadata:async()=>metadataSaves++},helper={getGlobalWorldbookNames:()=>[...globals],rebindGlobalWorldbooks:async ns=>globals=[...ns],deleteWorldbook:async n=>fail&&n==='旧书'?false:books.delete(n)};
 globalThis.fetch=async()=>({ok:true});return {context,helper,worldInfo:{world_info:{charLore:[extra]}},read:async n=>structuredClone(books.get(n)),names:['旧书'],books,card,extra,power,globals:()=>globals};}
try{
 await check('copy verification, character/global/chat/persona relinks and deletion succeed',async()=>{const f=fixture();await renameWorldbook({...f,oldName:'旧书',newName:'新书'});assert.ok(!f.books.has('旧书'));assert.equal(f.books.get('新书').entries[0].content,'untouched');assert.equal(f.card.data.extensions.world,'新书');assert.deepEqual(f.extra.extraBooks,['新书','其他书']);assert.deepEqual(f.globals(),['其他书','新书']);assert.equal(f.context.chatMetadata.world_info,'新书');assert.equal(f.power.persona_descriptions.fixture.lorebook,'新书');});
 await check('failed deletion rolls back bindings and keeps the original book',async()=>{const f=fixture(true);await assert.rejects(renameWorldbook({...f,oldName:'旧书',newName:'新书'}));assert.ok(f.books.has('旧书'));assert.ok(!f.books.has('新书'));assert.equal(f.card.data.extensions.world,'旧书');assert.deepEqual(f.globals(),['其他书','旧书']);assert.equal(f.context.chatMetadata.world_info,'旧书');});
 await check('name collision never overwrites an existing book',async()=>{const f=fixture();f.names.push('新书');await assert.rejects(renameWorldbook({...f,oldName:'旧书',newName:'新书'}));assert.ok(!f.books.has('新书'));});
}finally{globalThis.fetch=originalFetch;}
const raw=JSON.parse(await fs.readFile(new URL('../worldbook-seed.json',import.meta.url),'utf8')),other=JSON.parse(await fs.readFile(new URL('../worldbook-00.json',import.meta.url),'utf8')),before=parseWorldbook(composeWorldbooks([{name:'第一书',book:raw},{name:'旧书',book:other}])),after=parseWorldbook(composeWorldbooks([{name:'第一书',book:raw},{name:'新书',book:other}])),localPilot=before.pilots.find(p=>p.id==='ad-setsuna'),localMachine=before.machines.find(m=>referenceOrigin(m)?.originalId==='ad-exia');
await check('renaming a lower-priority book remaps private IDs and skill switches',()=>{const force={machineId:localMachine.id,pilotId:localPilot.id,stateId:'ad-2307',count:1,strategy:'attack',pilotOptions:{skills:{[Object.keys(localPilot.states[0].skills)[0]]:false}}},plan={battlefieldId:'pursuit-space',environmentId:'space',missionId:'annihilation',distanceM:2000,altitudeM:0,focus:'overall',mode:'auto',aForces:[force],bForces:[{machineId:'seed-duel',pilotId:'elite-pilot',stateId:'standard',count:1,strategy:'attack'}],maxSeconds:120},remapped=remapRenamedScenario(plan,before,after,'旧书','新书');assert.notDeepEqual(remapped.aForces[0].pilotOptions,force.pilotOptions);validateScenario(remapped,after);assert.equal(remapped.aForces[0].count,1);});
console.log(JSON.stringify({checks}));
