import {createHash} from 'node:crypto';
export function complete00({raw,entries,add,copy,machine,W,F,shield,field,templ}){
 const clean=s=>String(s).replace(/<%[\s\S]*?%>/g,'').replace(/\*\*/g,'');
 const section=(s,label)=>{const match=s.match(new RegExp('## [^\\n]*'+label+'[^\\n]*\\n([\\s\\S]*?)(?=\\n## |<\\/)'));return clean(match?.[1]||'');};
 const signature=name=>'ad-source-'+createHash('sha256').update(name).digest('hex').slice(0,14);
 const rows=()=>Object.values(entries).filter(e=>e.content.includes('<GWS_DATA>')).map(e=>JSON.parse(e.content.match(/<GWS_DATA>\s*([\s\S]*?)\s*<\/GWS_DATA>/)[1]));
 const names=new Set(rows().map(d=>d.name)),source=new Map(raw.filter(e=>e.comment.startsWith('核心设定·机体与装备:')).map(e=>[e.comment.slice('核心设定·机体与装备:'.length),e]));
 const weaponClass=n=>/獠牙|剑Bit|剪刀Bit/i.test(n)?'gn-fang':/Bit|浮游|遥控/i.test(n)?'gn-bit':/狙击/.test(n)?'gn-sniper':/火箭|破坏炮|米加炮|粒子炮/.test(n)&&/GN/.test(n)?'gn-bazooka':/导弹|鱼雷|火箭/.test(n)?'gn-missile':/光束剑|光束军刀|光束刃/.test(n)?'gn-saber':/GN.*(?:剑|刀|刃|锤|矛|鞭|爪)|(?:剑|刀|刃|锤|矛|鞭|爪).*GN/.test(n)?'gn-sword':/等离子.*(?:刃|刀)|高碳|震动|振动|实体刃|碳素(?:刀|爪)|线性(?:磁道矛|电磁针)/.test(n)?'ad-blade':/火神|机炮|机枪|机关炮/.test(n)?/GN|光束/.test(n)?'gn-vulcan':'ad-vulcan':/GN|光束|激光|镭射|等离子加农炮/.test(n)?/炮|加农/.test(n)?'gn-cannon':'gn-rifle':/线性|磁轨/.test(n)?'ad-linear':/炮|步枪|枪/.test(n)?'ad-mg':null;
 function weapons(body,ship=false){const sec=(section(body,'武装')||section(body,'装备'));if(/(?:没有|无|不具备)固定武装/.test(sec)&&!/^\s*-\s/m.test(sec))return [];const pieces=[...sec.matchAll(/^\s*-\s*([^\n：:]{1,70})[：:]/gm)].map(m=>m[1]);if(!pieces.length)for(const sentence of sec.split(/[。\n]/)){const matches=sentence.match(/(?:[\d.]+毫米(?:加农炮|机炮)|(?:GN|NGN)[A-Za-zⅡⅢⅣⅤ／/\s\-\u4e00-\u9fff]{0,18}?(?:光束剑|光束军刀|光束步枪|狙击步枪|光束手枪|导弹|鱼雷|加农炮|火箭炮|獠牙|光束机枪)|线性步枪|滑膛炮|高碳振动刃)/g);if(matches)pieces.push(...matches);}for(const match of sec.matchAll(/(?:GN火神炮|GN光束冲锋枪|GN冲锋枪|GN手枪|等离子加农炮|碳素爪|碳素刀|线性加农炮|激光加农炮|线性磁道矛|线性电磁针|GN粒子束炮|GN激光炮|镭射加农炮|激光炮|高射炮|防空激光密集方阵|GN破坏步枪|GN米加炮|GN火箭炮|GN剑|GN枪|GN加农炮|GN光束手枪|GN光束军刀|GN光束剑|对人机枪|大型磁轨炮|线性磁轨炮|磁轨炮|导弹发射器|鱼雷发射器)/g))pieces.push(match[0]);const out=[];for(const title of pieces){const name=title.replace(/\([^)]*\)|（[^）]*）/g,'').trim().slice(0,80);let template=weaponClass(name);if(!template||/太阳炉|推进|传感|通讯|通信|姿势|Trans-Am|Trans Am|力场|GN盾牌$|GN盾$|储存|容器|电容器|迷彩|审判|助推|稳定系统|复合装甲|光束盾|小型盾牌|复合盾/i.test(name))continue;if(ship&&['gn-rifle','gn-cannon','gn-bazooka'].includes(template))template='gn-ship-main';if(ship&&['gn-vulcan','ad-vulcan'].includes(template))template=template==='ad-vulcan'?'ad-ship-ciws':'gn-ship-ciws';if(ship&&template==='ad-linear')template='ad-ship-rail';const canonical=n=>n.replace(/\s|[×x]\s*\d+|^GN|发射器/g,'');if(out.some(w=>canonical(w.name)===canonical(name)||(!/×|x\s*\d/.test(name)&&canonical(w.name).includes(canonical(name)))))continue;const count=Number(name.match(/[×x]\s*(\d+)/)?.[1])||1,melee=['gn-saber','gn-sword','ad-blade'].includes(template),remote=['gn-bit','gn-fang'].includes(template);const w=remote?F(name,Math.min(24,count>1?count:6),template==='gn-fang',4,true):W(template,name,melee?1:/机枪|机炮|火神/.test(name)?3:/炮|狙击/.test(name)?2:/导弹|鱼雷/.test(name)?4:1);if(/导弹|鱼雷/.test(name))w.sim={...w.sim,ammo:Math.min(200,count>1?count*2:24)};if(count>1&&!melee&&!remote&&!/导弹|鱼雷/.test(name)&&count<=8)w.sim={...w.sim,burst:Math.min(6,count)};out.push({...w,id:'source-w'+(out.length+1)});}return out.slice(0,20);}
 const familyBase=n=>{const families=[['量子型00|00量子型','ad-qant'],['00.*强化|00.*七剑|七剑.*00|XN.*00','ad-00-raiser'],['能天使|正义女神','ad-exia'],['智天使','ad-cherudim'],['力天使|星水女神','ad-dynames'],['妖天使','ad-harute'],['堕天使|弓兵|战车女神','ad-arios'],['主天使','ad-kyrios'],['炽天使','ad-seravee'],['天使长|SEM','ad-seraphim'],['德天使|审判女神','ad-virtue'],['娜德雷','ad-nadleeh'],['座天使','ad-throne-eins'],['厄运|GN-X','ad-gnx'],['制定|暴徒','ad-enact'],['旗帜|狂风|实战','ad-flag'],['铁人|法统','ad-tieren'],['先驱|新驱','ad-ahead'],['再生|1.5高达|1高达','ad-reborns'],['加迪萨|加格|加农','ad-gadessa']];return families.find(([p])=>new RegExp(p).test(n))?.[1]||(/高达/.test(n)?'ad-0-gundam':'ad-gnx');};

 for(const [name,rec]of source){if(names.has(name)){const e=Object.values(entries).find(e=>{const m=e.content.match(/<GWS_DATA>\s*([\s\S]*?)\s*<\/GWS_DATA>/);return m&&JSON.parse(m[1]).name===name;});if(e){const d=JSON.parse(e.content.match(/<GWS_DATA>\s*([\s\S]*?)\s*<\/GWS_DATA>/)[1]);if(d.entityType==='ship'&&name!=='托勒密号'){const own=weapons(clean(rec.content),true);if(own.length)d.weapons=own;d.componentDefs=(d.componentDefs||[]).filter(c=>!c.slot||d.weapons.some(w=>w.slot===c.slot));const len=Number(clean(rec.content).match(/(?:全长|舰长)[^\d]{0,8}([\d.]+)\s*米/)?.[1]);if(len){d.renderProfile={shape:'ship',dimensions:[len,len*.22,len*.35]};d.sim.radiusM=Math.min(500,len*.3);}e.content='<GWS_DATA>\n'+JSON.stringify(d,null,2)+'\n</GWS_DATA>';}}continue;}if(name==='铁人式'){const baseEntry=Object.values(entries).find(e=>e.content.includes('"id": "ad-tieren"'));baseEntry.key=[...new Set([...baseEntry.key,name,...(rec.key||[])])];names.add(name);continue;}const body=clean(rec.content),identity=section(body,'身份'),armament=section(body,'武装'),ship=(/级|号|母舰|空母|运输舰/.test(name)||/本舰|航宙舰|宇宙舰|运输(?:母)?舰|战舰|巡洋舰|工厂舰|探索船/.test(identity))&&!/高达|铁人式/.test(name)&&name!=='连恩号',small=['集装箱','运输机','自动机器人','工作装载机','出租车摩托','VTOL机','小型太空船','连恩号','强袭集装箱'].includes(name),baseId=ship?'ad-ptolemaios-ii':small?'ad-flag':familyBase(name);const d=structuredClone(machine(baseId));d.id=signature(name);d.name=name;for(const k of ['aliases','selection','note','forms','stealth','loadoutSystem'])delete d[k];d.weapons=weapons(body,ship);
 if(name==='核弹'){templ(signature(name),name,'gn-missile',{damage:250,ammo:1,burst:1,blastRadiusM:700,energyCost:0,damageClass:'physical',beamFraction:0,cooldownS:20},{tags:['area-blast','nuclear']});names.add(name);continue;}
 if(name==='天人号'){d.sim.structure=18000;d.sim.armor=7000;d.sim.maxSpeedMps=45;d.sim.radiusM=500;d.renderProfile={shape:'ship',dimensions:[15000,2200,4000]};d.sim.massKg=10000000;d.sim.thrustN=10000000;}
 if(name==='死兆炮'){d.entityType='turret';d.weapons=[{...W('gn-ship-main','自由电子激光炮',1,{damage:400,energyCost:600,cooldownS:30,windupS:3,arcYawDeg:8,arcPitchDeg:8,rangeM:60000,effectiveRangeM:60000,preferredRangeM:30000}),id:'source-w1'}];d.sim.maxSpeedMps=0;d.sim.thrustN=0;d.sim.energyCapacity=1000;d.sim.energyRegen=35;d.sim.structure=7000;d.sim.armor=2500;d.sim.radiusM=400;}
 else if(ship)d.entityType='ship';else if(small)d.entityType=/集装箱|小型太空船/.test(name)?'pod':'vehicle';else if(/\bMA\b|大型MA|水中用MA|小型固定翼MA|机动装甲|机动堡垒/.test(identity))d.entityType='ma';else d.entityType='ms';
 const noWeapons=/无武装|没有固定武装|无固定武装/.test(armament),ground=/陆战|陆地|地面专用|沙漠|悬浮坦克|出租车摩托|工作装载机|自动机器人/.test(name),water=/水下|水中用|潜航|潜水/.test(identity),spaceOnly=/轨道外装|宇宙|空间型/.test(name);const powerText=identity+' '+armament+' '+section(body,'性能'),tau=/拟似太阳炉|GN太阳炉τ型|GN Drive Tau/.test(powerText),conventional=!/GN太阳炉|太阳炉|粒子推进|GN推进|GN电容/.test(powerText),power=tau?'gn-tau':/GN电容器|粒子储存|粒子储藏槽|储藏槽型/.test(powerText)&&!/搭载(?:原装|原型|两台|一具|一台)?GN太阳炉/.test(powerText)?'gn-capacitor':conventional?'battery':'gn-drive';d.powerSystem={type:power,ratedOutputKw:null,njc:false,receiveDeuterion:false,supplyRate:0,supplyRangeM:0};d.sim.unlimitedEnergy=power==='gn-drive'||ship;d.sim.totalEnergy=d.sim.unlimitedEnergy?1000000:power==='gn-tau'?14000:8000;
 d.tags=['anno-domini',...(ground?['ground-combat']:water?['water-combat']:spaceOnly?['space-combat']:['space-combat','ground-combat','air-combat'])];if(!conventional&&/Trans[- ]?Am|トランザム/i.test(armament+section(body,'性能'))&&!/不具.*Trans-Am|无法.*Trans-Am/.test(armament))d.tags.push('trans-am');if(/VEDA/.test(identity+armament))d.tags.push('veda-linked');if(name==='ELS00量子型')d.powerSystem.type='gn-drive';if(/大型|重型|炮击/.test(name))d.sim.maxSpeedMps*=.85;if(/高机动|突进|勇者|狂风/.test(name)){d.sim.maxSpeedMps*=1.1;d.sim.thrustN*=1.15;}
 const mass=Number(body.match(/(?:本体重量|本体质量|重量)[^\d]{0,12}([\d.]+)\s*(?:吨|t)/)?.[1]),height=Number(body.match(/(?:头顶高|全高|高度)[^\d]{0,8}([\d.]+)\s*米/)?.[1]);if(mass>=1){d.sim.thrustN*=mass*1000/d.sim.massKg;d.sim.massKg=Math.min(10000000,mass*1000);}if(height>=1){d.sim.radiusM=Math.min(500,height*.55);d.renderProfile.dimensions=[height*.75,height,height*.65];}
 if(ship){const len=Number(body.match(/全长[^\d]{0,8}([\d.]+)\s*米/)?.[1]);if(len){d.renderProfile={shape:'ship',dimensions:[Math.min(15000,len),Math.min(3000,len*.22),Math.min(4500,len*.35)]};d.sim.radiusM=Math.min(500,len*.3);}}else if(small){d.sim.massKg=5000;d.sim.thrustN=70000;d.sim.structure=80;d.sim.armor=25;d.sim.radiusM=5;d.renderProfile={shape:d.entityType==='pod'?'capsule':'vehicle',dimensions:[12,5,7]};d.sim.maxSpeedMps=/出租车摩托|工作装载机|自动机器人/.test(name)?40:180;d.sim.groundSpeedMps=30;d.componentDefs=[];d.defenses=[];}
 d.defenses=[...(/(?:GN)?(?:全装甲|全护盾|盾牌|盾)/.test(armament)&&!noWeapons?[shield()]:[]),...(/GN力场|GNフィールド/.test(armament)?[field()]:[])];d.componentDefs=(d.componentDefs||[]).filter(c=>!c.slot||d.weapons.some(w=>w.slot===c.slot));d.combatant=d.weapons.length>0;
 if(/变形|飞行形态|MA形态/.test(identity+section(body,'外观')+armament)&&!ship&&!small){const ids=d.weapons.map(w=>w.id);d.forms=[{id:'ms',name:'MS形态',speedFactor:1,thrustFactor:1,turnFactor:1,tags:d.tags,weaponIds:ids},{id:'ma',name:'飞行／炮击形态',speedFactor:1.2,thrustFactor:1.15,turnFactor:.8,tags:d.tags,weaponIds:d.weapons.filter(w=>!['gn-saber','gn-sword','ad-blade'].includes(w.template)).map(w=>w.id)}];}
 d.sim.groundSpeedMps=Math.min(d.sim.groundSpeedMps||0,d.sim.maxSpeedMps);const base=machine(baseId);if(!ship&&!small&&base&&base.name!==name&&name.includes(base.name.replace('高达','')))d.selection={familyId:base.id,familyName:base.name,variantName:name};add(d,rec.key||[]);names.add(name);
 }
 for(const rec of raw.filter(e=>e.comment.startsWith('角色:'))){const name=rec.comment.slice(3);if(names.has(name))continue;const body=clean(rec.content),pilot=/驾驶(?:员|经历|MS|高达|机|铁人|制定|旗帜|厄运)|机师|Gundam Meister|机动战士驾驶员|高达驾驶员/.test(body),command=/舰长|舰队指挥|战术预报|指挥官/.test(body),blade=/近战|格斗|突击|剑术/.test(body),sniper=/狙击|射击技术|精准射击/.test(body),ace=/冯恩·史帕克|哈那优|毕赛德|蕾蒂西亚|葛拉贝|E·A·雷/.test(name);const base=structuredClone(rows().find(d=>d.id===(blade?'ad-setsuna':sniper?'ad-neil':command?'ad-sumeragi':'ad-sergei')));base.id=signature(name);base.name=name;delete base.aliases;base.templates=[ace?'ace':pilot||command?'elite':'common'];const state=structuredClone(base.states.at(-1));state.id='standard';state.name=pilot?'驾驶配置':command?'指挥配置':'随舰／非战斗配置';state.sim={reactionS:ace?.115:pilot?.15:.25,aim:ace?.91:pilot?.78:.45,tracking:ace?.92:pilot?.78:.5,maneuver:ace?.92:pilot?.78:.5,composure:/冲动|鲁莽|好战/.test(body)?.62:.8,melee:ace?.93:pilot?.75:.42};state.skills={};if(/希克萨·费米|哈那优|毕赛德·佩因|葛拉贝·拜欧雷特|蕾夫·蕾奇塔缇万/.test(name))state.skills['gn-super-soldier']=true;if(/沙慈·克洛斯罗德|雪儿·亚克斯迪卡/.test(name))state.skills['gn-haro']=true;if(pilot&&/高达|GN|天使|勇者/.test(body))state.skills['gn-trans-am']=true;state.traits={driftShot:pilot,rationalRetreat:!/好战|鲁莽|嗜战/.test(body),returnSlash:blade,antiFunnel:ace};if(!pilot&&!command){state.strategies={'mission-retreat':1.6,'energy-reserve':1.4,'safe-recovery':1.4,'gun-range':.5};state.capabilities={spatialAwareness:.5,precision:.5,teamwork:.75,energyDiscipline:.8};base.note='非战斗人员；随舰与撤离用配置。';}if(name==='沙慈·克洛斯罗德'){base.templates=['common'];state.sim={reactionS:.18,aim:.68,tracking:.82,maneuver:.75,composure:.72,melee:.55};state.skills={'gn-haro':true};state.strategies={'cover-ally':1.7,'energy-reserve':1.4,'mission-retreat':1.3,'melee-pressure':.3};}base.states=[state];add(base,rec.key||[]);names.add(name);}
 for(const entry of Object.values(entries)){if(!entry.content.includes('<GWS_DATA>'))continue;const d=JSON.parse(entry.content.match(/<GWS_DATA>\s*([\s\S]*?)\s*<\/GWS_DATA>/)[1]),rec=source.get(d.name)||raw.find(e=>e.comment==='角色:'+d.name);if(rec)entry.key=[...new Set([d.name,...(entry.key||[]),...(rec.key||[])])].slice(0,24);}
 return {equipment:source.size,characters:raw.filter(e=>e.comment.startsWith('角色:')).length};
}
